config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "tops#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :tops, only: [:index, :edit, :update]
  get "/mypage/:id", to: "tops#show", as: "mypage"
  get "/likelist/:id", to: "tops#like", as: "likelist"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "/contacts", to: "contacts#index", as: "contacts"
  resources :contacts, only: %i[index create]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # バリデーション
  validates :content, presence: true, length: { maximum: 500 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @post, notice: "コメントを書き込みました。"
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post, notice: "コメントを削除しました。"
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/views/comments/_form.html.erb
<!---- コメント入力フォーム ----->
<%= form_with(model: [post, comment], url: post_comments_path(@post) ) do |f| %>
    <%= f.text_area :content, required: true, size: "60x5", autocomplete: "content_cont", class:"area-field" %>
    <div class="d-flex justify-content-end">
      <%= f.submit "書き込む", class:"submit-btn comment-btn" %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<!---- コメント内容 ----->
<p class="comment-count">コメント数<%= comments.count %>件</p>
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <div class="comment-box border-left border-success bg-light" style="padding:20px;">
      <p> <%= comment.user.username %> <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></p>
      <%= simple_format(h comment.content) %>
      <% if comment.user == current_user %>
        <div class="d-flex justify-content-end">
          <%= link_to "削除", post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, data: { confirm: "削除しますか？" }, class: "btn btn-outline-danger option-btn" %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>