config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "tops#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :tops, only: [:index, :edit, :update]
  get "/mypage/:id", to: "tops#show", as: "mypage"
  get "/likelist/:id", to: "tops#like", as: "likelist"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "/contacts", to: "contacts#index", as: "contacts"
  resources :contacts, only: %i[index create]
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  PER_PAGE = 5

  def index; end

  def show
    @user = current_user
    @likes = Like.where(user_id: @user.id).all
  end

  def like
    @user = current_user
    @likes = Like.where(user_id: @user.id).all.page(params[:page]).per(PER_PAGE).order(created_at: :desc)
  end
end

app/views/tops/_list.html.erb
<% @likes.each do |like| %>
  <div class="comment-box border-left border-success bg-light" style="padding:20px;">
    <a> 名前：<%= like.post.user.username %></a><br>
    <a>タイトル：<%= like.post.title %></a><br>
    <p><%= like.post.content %></p>
  </div>
<% end %>

app/views/tops/index.html.erb
<div class="container">
  <div class="row top-container d-flex align-items-center justify-content-center bg-success">
    <h2 class="title text-white bg-info">おうち時間〜spendtime〜</h2>
  </div>
  <div class="message-title d-flex align-items-center justify-content-center"> 
    <h3 class="title-text font-weight-bolder text-success">おうち時間〜spendtime〜とは<h3>
  </div>
  <div class="message-text font-weight-bolder title-explanation d-flex align-items-start justify-content-center"> 
    自宅での遊びや趣味を共有するコミュニティサイトです。<br>
    自宅での過ごし方をみんなで共有し楽しい時間を増やしましょう。
  </div>
  <div class="acount-wrapper">
    <div class="menu-wrapper d-flex align-items-center justify-content-center">
      <h4 class="menu-select text-success" style="height:60px;">〜〜ご利用の方はこちら〜〜</h4>
    </div>
    <div class="row bg-success menu-select-btn d-flex align-items-center justify-content-center">
      <% if user_signed_in? %>
      <%# ログイン済みの表示 %>
        <%= link_to "投稿一覧ページ", posts_path, class:"select-btn btn btn-info col-sm" %><br>
        <%= link_to "新規投稿", new_post_path, class:"select-btn btn btn-info col-sm" %>
      <% else %>
        <%# 非ログイン時の表示 %>
        <%= link_to "ログイン", new_user_session_path, class:"select-btn btn btn-info col-sm-4" %><br>
        <%= link_to "新規登録", new_user_registration_path, class:"select-btn btn btn-info col-sm-4" %><br>
        <%= link_to "ゲストログイン", users_guest_sign_in_path,method: :post, class:"guest-btn select-btn btn btn-info col-sm-4" %>
      <% end %>
    </div>
  </div>
  <div class="infomation-container d-flex align-items-start justify-content-center">
    <h4 class="infomation-title">お知らせ</h4>
  </div>
  <div class="infomation-text">・今後のお知らせはここに記載します。</div>
</div>

app/views/tops/like.html.erb
<div class="top-container d-flex align-items-center justify-content-center bg-success">
  <h2 class="content-title text-white font-weight-bolder">---Goodリスト---</h2>
</div>
<%= render "list" %>
<div class="paginate-btn">
  <%= paginate @likes %>
</div>
<hr>
<p class="d-flex justify-content-end"><%= link_to "マイページへ", mypage_path(current_user), class:"page-post text-white btn btn-info" %></p>

app/views/tops/show.html.erb
<div class="top-container d-flex align-items-center justify-content-center bg-success">
  <h2 class="content-title text-white font-weight-bolder">〜マイページ〜</h2>
</div>
<div class="mymenu-wrapper d-flex align-items-center justify-content-center">
  <h3 class="name-text text-success font-weight-bolder"><%= "ー #{current_user.username}さん ー" %></h3>
</div>

<div class="row menu-btn d-flex align-items-center justify-content-center">
  <%= link_to "Goodリスト", likelist_path, class:"btn btn-info mymenu-select col-sm" %><br>
  <%= link_to "アカウント編集", edit_user_registration_path, class:"btn btn-info mymenu-select col-sm" %><br>
  <div class="w-100"></div>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn btn-info mymenu-select col-sm" %><br>
  <%= link_to "投稿一覧へ", posts_path, class:"btn btn-info mymenu-select col-sm" %>
</div>