config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "tops#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :tops, only: [:index, :edit, :update]
  get "/mypage/:id", to: "tops#show", as: "mypage"
  get "/likelist/:id", to: "tops#like", as: "likelist"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "/contacts", to: "contacts#index", as: "contacts"
  resources :contacts, only: %i[index create]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 1000 }

  def liked_by?(user)
    likes.any? { |like| like.user_id == user.id }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[edit update destroy]

  PER_PAGE = 5

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(PER_PAGE).includes(:user, :likes).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.create!(post_params)
    redirect_to post
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user, :post).order(created_at: :desc)
  end

  def edit; end

  def update
    @post.update!(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy!
    redirect_to @post
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_path, alert: "権限がありません" if @post.nil?
  end
end

app/views/posts/_dislike.html.erb
<%= link_to post_likes_path(post), {method: :post, remote: true} do %>
  <i class="far fa-thumbs-up"></i>
<% end %>
<%= post.likes_count %>

app/views/posts/_form.html.erb
<div class="d-flex justify-content-center">
  <%= form_with model: @post, local: true do |form| %>
    <h5 class="d-flex justify-content-center">
      <%= form.label :title, class:"post-title font-weight-bolder" %><br />
    </h5>
    <div class="d-flex justify-content-center">
      <%= form.text_field :title, required: true, class:"text-area-field" %>
    </div>
    
    <h5 class="d-flex justify-content-center">
      <%= form.label :content, class:"post-title font-weight-bolder" %><br />
    </h5>
    <div class="d-flex justify-content-center">
      <%= form.text_area :content, required: true, size: "50x10", class:"text-area-field" %>
    </div>
    <br>
    <div class="d-flex justify-content-end">
      <%= form.submit "送信", class:"submit-btn" %>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-end">
  <%= link_to "投稿一覧へ", posts_path, class:"page-post text-white btn btn-info" %>
</div>

app/views/posts/_like.html.erb
<%= link_to post_likes_path(post), {method: :delete, remote: true} do %>
  <i class="fas fa-thumbs-up"></i>
<% end %>
<%= post.likes_count %>

app/views/posts/_post.html.erb
<p>投稿者： <%= post.user.username %></p>
<p class="font-weight-bolder">タイトル：<%= post.title %></p>
<p id="post-<%= post.id %>">
  <% if post.liked_by?(current_user) %>
    <%= render "like", post: post %>
  <% else %>
    <%= render "dislike", post: post %>
  <% end %>
</p>
<p class="d-flex justify-content-end">
  <%= link_to "詳細", post, class:"btn btn-outline-success option-btn" %>
  <% if current_user.id == post.user_id %>
    <%= link_to "編集", edit_post_path(post), class:"btn btn-outline-primary option-btn" %>
    <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？" }, class:"btn btn-outline-danger option-btn" %>
  <% end %>
</p>
<hr>

app/views/posts/edit.html.erb
<div class="top-container d-flex align-items-center justify-content-center bg-success">
  <h2 class="content-title text-white font-weight-bolder">〜編集〜</h2>
</div>
<%= render "form" %>

app/views/posts/index.html.erb
<div class="top-container d-flex align-items-center justify-content-center bg-success">
  <h2 class="content-title text-white font-weight-bolder">〜投稿一覧〜</h2>
</div>
<hr>
<div class="list-search bg-light">
  <h5 class="search-title">キーワードで検索</h5>
  <%= search_form_for @q do |f| %>
    <%= f.search_field :title_cont, placeholder: "タイトルで検索", autocomplete: "title_cont" %>
    <%= f.search_field :content_cont, placeholder: "内容で検索", autocomplete: "content_cont" %>
    <%= f.submit "検索", class:"submit-btn" %>
  <% end %>
  <div class="d-flex justify-content-end">
    <div class="search-clear">
      <%= link_to "検索をクリア", posts_path, class:"clear-btn text-white btn btn-info" %>
    </div>
  </div>
</div>
<hr>
<div class="post-list bg-light">
  <%= render @posts %>
</div>
<div class="paginate-btn">
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="top-container d-flex align-items-center justify-content-center bg-success">
  <h2 class="content-title text-white font-weight-bolder">〜新規投稿〜</h2>
</div>
<%= render "form" %>

app/views/posts/show.html.erb
<!-- 投稿内容 -->
<div class="top-container d-flex align-items-center justify-content-center bg-success">
  <h2 class="content-title text-white font-weight-bolder">〜投稿詳細〜</h2>
</div>
<div class="post-content bg-light">
  <p><%= @post.user.username %> <%= @post.created_at.strftime('%Y/%m/%d %H:%M:%S') %></p>
  <p class="font-weight-bolder"><%= @post.title %></p>
  <p><%= simple_format(h @post.content) %></p>
  <p id="post-<%= @post.id %>">
    <% if @post.liked_by?(current_user) %>
      <%= render "like", post: @post %>
    <% else %>
      <%= render "dislike", post: @post %>
    <% end %>
  </p>

  <!-- 投稿編集と削除 -->
  <% if current_user.id == @post.user_id %>
    <p class="d-flex justify-content-end">
      <%= link_to "編集", edit_post_path(@post), class:"btn btn-outline-primary option-btn" %>
      <%= link_to "削除", post_path(@post), method: :delete, data: { confirm: "削除しますか？" }, class:"btn btn-outline-danger option-btn" %>
    </p>
  <% end %>
</div>
<div class="d-flex justify-content-end">
  <p class="back-box">
    <%= link_to "投稿一覧へ", 'javascript:history.back()', class:"page-post text-white btn btn-info" %>
  </p>
</div>

<!-- コメント一覧 -->
<% if user_signed_in? %>
  <div class="comment-create">
    <h4 class="comment-title font-weight-bolder">コメントを投稿する</h4>
    <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
  </div>
<% end %>
<hr>
<h4 class="text-comments">コメント一覧</h4>
<div class="comments-area">
  <%= render partial: 'comments/index', locals: { comments: @comments } %>
</div>


<div class="d-flex justify-content-end">
  <p class="back-box">
    <%= link_to "投稿一覧へ", 'javascript:history.back()', class:"page-post text-white btn btn-info" %>
  </p>
</div>