config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "tops#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :tops, only: [:index, :edit, :update]
  get "/mypage/:id", to: "tops#show", as: "mypage"
  get "/likelist/:id", to: "tops#like", as: "likelist"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "/contacts", to: "contacts#index", as: "contacts"
  resources :contacts, only: %i[index create]
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <p class="flash-msg"><%= msg %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer bg-success">
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center" style="height:100px;">
      <div class="col footer-text text-dark">Copyright © おうち時間 All rights reserved.</div>
      <%= link_to "お問い合わせ", contacts_path, class: "col contact nav-link text-light active" %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-success fixed-top">
  <%= link_to "おうち時間~SpendTime~", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button"
    data-toggle="collapse"
    data-target="#navmenu1"
    aria-controls="navmenu1"
    aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navmenu1">
    <div class="navbar-nav">
      <% if user_signed_in? %>
        <%= link_to "TOPへ", root_path, class: "nav-item nav-link" %>
        <%= link_to "投稿", new_post_path, class: "nav-item nav-link" %>
        <%= link_to "投稿一覧ページ", posts_path, class: "nav-item nav-link" %>
        <%= link_to "マイページ", mypage_path(current_user), class: "nav-item nav-link" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to "TOPへ", root_path, class: "nav-item nav-link" %>
        <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link" %>
        <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link" %>
        <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-item nav-link" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpendTimeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      
      <hr>
      <div class="base-container">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>